" vimrc - Vim configuration that follows Pindorama's
" coding-style.
" Copyright (C) 2021: Caio Novais (chexier).
" Inclusion of UTF-8 encoding, wildmenu and incsearch by
" Luiz Antônio (takusuman).

" Basic options
"" UTF-8
set encoding=utf-8
set fileencoding=utf-8
"" Syntax highlighting
syntax on
filetype plugin indent on
set number
set incsearch
set wildmenu
set nocompatible

" Indent without hard tabs
set expandtab
set shiftwidth=2
set softtabstop=2

" Limit lines to be at most 80 characters long
set textwidth=80

" Enable True Colors
set termguicolors

" Automatically remove all trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e

" ~/ Clean-up
let g:netrw_dirhistmax=0
set viminfo=""
